name: studying
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      - name: setup
        run: make setup
      - name: test
        run: make test
      - name: lint
        run: make lint
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
      - uses: hexlet-components/hello-from-hexlet-action@release

